apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: sample-app
      annotations:
        pod.boostport.com/vault-approle: sample-app
        pod.boostport.com/vault-init-container: install
    spec:
      initContainers:
      - name: install
        image: boostport/kubernetes-vault-init:0.4.4
        imagePullPolicy: Always
        env:
        - name: VAULT_ROLE_ID
          value: 3080af65-9221-fb00-951a-7dd6841012ba
        volumeMounts:
        - name: vault-token
          mountPath: /var/run/secrets/boostport.com
      containers:
      - name: sample-app
        image: boostport/kubernetes-vault-sample-app:0.4.4
        volumeMounts:
        - name: vault-token
          mountPath: /var/run/secrets/boostport.com
      volumes:
      - name: vault-token
        emptyDir: {}
